### PR TITLE
Rename and Satisfy WPCS

### LINKED ISSUE #6: Name change
What do you think about `\WP_CLI::add_command( 'db change-prefix', 'WP_CLI_Rename_DB_Prefix' );` ?

### PR DESCRIPTION
**Pull request by szepeviktor**
- renamed command
- added my alias 😉 
- renamed main php file
- renamed class
- moved todos to their place

Fixes #6

### CODE REVIEW

**Comment by szepeviktor** [comment]
@iandunn Do you like it?
I think it is much cleaner now.

**Comment by iandunn** [comment]
Thanks for the PR :)

Would you mind reverting all the unrelated changes, like moving comments to their own line, changing double quotes to single quotes, removing backticks around filesnames, adding periods in comments, etc?

They add a lot of diff noise, making it harder to review. If they're important to you, you could move them to a separate commit instead of removing them.

**Comment by szepeviktor** [comment]
Do you mean to separate WPCS and renaming?

**Comment by iandunn** [comment]
Yeah, it's a best practice to keep commits atomic.

https://seesparkbox.com/foundry/atomic_commits_with_git
https://www.freshconsulting.com/atomic-commits/

Which sniff are you using?

**Comment by szepeviktor** [comment]
Standard WPCS minus "tabs as indent"

**Pull request closed without merging**
